# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-15 15:22
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='movies_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, size=None),
        ),
    ]
